# -*- coding: utf-8 -*-
"""Inhoud / content for the Skyhaven Squad storybooks (EN + AF).

Paragraph kinds:  str = normal text,  ("q", text) = ticket / quote box,  ("list", [..]) = numbered list.
"""

EN = dict(
    code="EN",
    file="Daniel_and_the_Skyhaven_Squad_EN.pdf",
    title="Daniel and the Skyhaven Squad",
    cover_top="A STORY ABOUT FRIENDSHIP, COURAGE AND KINDNESS",
    cover_for="Written for Daniel and his squad",
    cover_names="Riley · Mason · James · Raffi · Ethan · Kai",
    ui=dict(
        chapter="CHAPTER", challenge="SQUAD CHALLENGE", the_end="THE END",
        the_end_sub="(for now!)", dedication_title="For Daniel",
        dedication=("This book is for Daniel, the best leader a squad could have, and for his friends "
                    "Riley, Mason, James, Raffi, Ethan and Kai. Real friends make every adventure better."),
        squad_title="Meet the Squad", talent="Super-talent", motto="Motto",
        map_title="Map of Skyhaven Island", map_sub="Follow the path to the Storm Tower! Tick each stop when you finish the chapter.",
        quiz_title="Squad Quiz", quiz_sub="How well did you read? Answer in full sentences. Answers are at the bottom of the page.",
        answers="Answers:", next_title="Your Next Adventure!",
        next_text="Where should the Skyhaven Squad go next? Draw the place and write what happens.",
        draw="Draw it here:", write="Write about it:", page="Page", fan="",
    ),
    map_stops=["Landing", "Wobbly Bridge", "Chasm of Chomp", "Riddle Gate", "Cave of Echoes", "Storm Tower"],
    squad=[
        ("Daniel", "Leader and Listener", "Together we can do anything!", "#5B2A9E"),
        ("Riley", "Fastest Feet", "Never stop running!", "#E4572E"),
        ("Mason", "Master Builder", "I can build that.", "#2D9CDB"),
        ("James", "Joke Machine", "Laughter is a superpower!", "#E0A800"),
        ("Raffi", "Bravest Heart", "Be brave, be kind.", "#2EAD6B"),
        ("Ethan", "Super Brain", "Think first, then act.", "#7B4BC8"),
        ("Kai", "Sky Pilot", "Stay calm and fly high.", "#17A2B8"),
    ],
    chapters=[
        dict(title="The Golden Ticket", scene="ticket", paras=[
            "It was the first day of the school holidays, and Daniel was bored. Not a little bit bored. Super-mega-extra bored.",
            "He was lying on his bed, tossing a ball at the ceiling, when something went CLINK inside his backpack.",
            "“That's weird,” said Daniel. “I didn't pack anything that clinks.”",
            "He unzipped the bag and pulled out a shiny golden ticket. It glowed like a tiny sun. In curly purple letters it said:",
            ("q", "SKYHAVEN NEEDS A HERO SQUAD!<br/>Seven players wanted. The bus leaves at 10 o'clock sharp. Don't be late!"),
            "Daniel looked at his clock. It said 9:58.",
            "“TWO MINUTES?!” he yelled.",
            "He grabbed his phone and sent the fastest message of his life: “EMERGENCY! Golden ticket! Squad needed NOW! Meet outside!”",
            "Six replies pinged back before he even found his shoes. Riley: “Running!” Mason: “Bringing my tools.” James: “Is this a prank? I LOVE it.” Raffi: “Coming! I'm brave!” Ethan: “Interesting. Calculating the fastest route.” Kai: “I'm already looking at the sky.”",
            "Within one minute, six friends skidded around the corner. Riley arrived first (of course). Mason clanked along in a toolbelt. James was laughing already. Raffi was wearing a superhero cape. Ethan was holding a map. Kai had a kite sticking out of a backpack.",
            "Then, at exactly 10 o'clock, the sky went HONK HONK! A giant blue bus with spinning silver propellers came whirling down and landed right in Daniel's street.",
            "The doors swung open. “All aboard!” squawked a voice.",
        ], challenge="If YOU found a golden ticket, where would you want it to take you?"),
        dict(title="All Aboard the Sky Bus", scene="bus", paras=[
            "Inside, the bus smelled like pancakes. The driver was a giant green parrot in a tiny captain's hat.",
            "“Welcome aboard, squad!” squawked Captain Pancake. “Keep your hands inside the bus, your feet off the seats, and your snacks in your tummies!”",
            "The bus lifted off with a WHOOOOSH. Houses turned into toys. Cars turned into ants. Daniel pressed his nose against the window and grinned. Then he looked around at his friends.",
            "Riley was the fastest runner in the whole school. Riley's shoelaces were always double-knotted, just in case.",
            "Mason could build anything out of anything. Once, Mason made a skateboard from a cereal box and three spoons. (It only worked a little bit.)",
            "James was the funniest kid anyone knew. James had a joke for every day of the year, and for leap years too.",
            "Raffi was the bravest. Raffi once patted a dog bigger than a sofa and said, “Good boy!”",
            "Ethan was the smartest. Ethan could solve a puzzle faster than you could say “puzzle.”",
            "Kai was the calmest, and the best at flying kites. Kai's kites went higher than the clouds.",
            "And Daniel? Daniel was the squad's leader, because Daniel was a great listener and made everybody feel part of the team.",
            "“So what's the mission?” asked Daniel.",
            "Captain Pancake's face turned serious. “Skyhaven Island floats because of the Great Golden Star. Last night, the Storm stole it. Now the island is sinking, a little more every hour. If we don't get the Star back, Skyhaven will crash!”",
            "“Don't worry,” said Daniel. “We'll get it back. Together.”",
            "Out of the window, a floating island appeared above the clouds, with waterfalls pouring UP into the sky. “Next stop,” squawked Captain Pancake, “Skyhaven!”",
        ], challenge="Which friend's talent would you most love to have? Why?"),
        dict(title="Skyhaven in Trouble", scene="island", paras=[
            "The bus landed with a bounce. Everything on Skyhaven was a little bit tilted. A bench slid by. A watering can rolled away. James had just been handed an ice cream when the ground tipped, and the ice cream slid off its cone. “My ice cream is escaping!” wailed James.",
            "A tiny llama in a giant top hat was standing on a box. “I am Mayor Fluff,” said the llama. “Thank goodness you're here!”",
            "The Mayor unrolled a long scroll. “The Storm lives in the Storm Tower, at the top of Crooked Mountain. To get there, you must pass five tests:”",
            ("list", ["The Wobbly Bridge", "The Chasm of Chomp", "The Riddle Gate", "The Cave of Echoes", "The Storm Tower itself"]),
            "“Easy peasy,” said James. Everybody looked at James. “...Okay, maybe not easy. But peasy.”",
            "Mayor Fluff gave every member of the squad a golden badge shaped like a star. Daniel pinned his on and felt a warm tingle. “Squad,” said Daniel, “let's go save Skyhaven!”",
            "The squad marched toward Crooked Mountain. Behind them, the island tilted a tiny bit more. Tick-tock, tick-tock.",
        ], challenge="Make up a funny name for a place on Skyhaven Island. What would it be?"),
        dict(title="Riley and the Wobbly Bridge", scene="bridge", paras=[
            "The first test was the Wobbly Bridge. It was made of old wooden planks, hanging over a river of white, fluffy clouds. And it was wobbling like jelly on a trampoline.",
            "WHOOOSH! A strong gust of wind blew. Two planks flew off and spun away into the sky.",
            "“Nobody panic,” said Daniel. “Riley, what do you see?”",
            "Riley watched the bridge carefully. “The wind comes in waves,” said Riley. “Big gust... pause... big gust... pause. If we run during the pause, we'll make it!”",
            "“Follow my footsteps,” said Riley. “Step where I step!”",
            "Riley counted: “One... two... THREE!” and zoomed across like a rocket. Skip-skip-hop! On the other side, Riley waved both arms.",
            "One by one, the squad followed. Mason slid. Ethan counted out loud. Raffi was brave until the bridge went wobble-wobble, then Raffi said, “Eeeek!” but kept going. James was laughing so hard that James nearly fell off, but Kai grabbed a hand just in time.",
            "Daniel was last. WHOOSH! The wind blew, but Daniel waited for the pause, then ran with all the speed his legs had. He leaped onto solid ground, and the bridge spun away behind him.",
            "At the end of the bridge, a little silver key hung from a hook. Riley picked it up. “One key down. Four tests to go!”",
        ], challenge="Riley spotted a pattern in the wind. Can you find a pattern in your classroom or at home?"),
        dict(title="Mason's Big Build", scene="chasm", paras=[
            "The next test was the Chasm of Chomp. It was a gigantic gap in the ground, so wide that the other side looked tiny. Down at the bottom, something went CHOMP CHOMP CHOMP.",
            "“Nope,” said James. “I'm not falling into that.”",
            "Big floating rocks and old planks drifted past in the air. Mason's eyes lit up. “I can build with those,” said Mason.",
            "“How much do we need?” asked Daniel. Ethan whipped out a measuring tape. “The gap is exactly 12 meters,” said Ethan. “We'll need at least 13 meters of bridge to be safe. And a sturdy ramp at each end.”",
            "“Perfect,” said Mason, cracking both knuckles. “Everybody, I need teamwork.”",
            "Everyone got a job. Riley raced around collecting planks. Kai tied ropes with perfect knots. Raffi held the ladder. James told jokes to keep everybody cheerful (“Why was the math book sad? It had too many problems!”). Ethan checked every measurement twice. Daniel passed tools to Mason and said, “You've got this.”",
            "Mason hammered, sawed and wiggled. BANG! CLANG! CLUNK! Slowly a bridge grew across the chasm, with railings and everything.",
            "Down in the chasm, the CHOMP sound got louder. “Don't look down,” said Daniel. “Look at the bridge. Look at your friends.” One by one they crossed. Halfway over, Raffi peeked over the edge. “Squad, the chomper is a hamster!” It was the size of a football, with a wiggly nose. Raffi tossed it half a sandwich. CHOMP! The hamster purred.",
            "On the other side, Mason patted the last plank. “Told you I can build anything out of anything.”",
        ], challenge="What would YOU build to cross the chasm? Draw it!"),
        dict(title="The Riddle Gate", scene="gate", paras=[
            "At the end of a long, winding path stood a huge stone gate, with a giant face carved in the middle. The face had sleepy eyes and a very long mustache.",
            "“I am Gus, the Gatekeeper,” rumbled the gate. “To pass, you must answer my riddle. You get three guesses.”",
            "The gate cleared its throat. “I have keys, but no locks. I have space, but no room. You can enter, but you can't go inside. What am I?”",
            "“A piano?” guessed Raffi. “Nope,” said Gus. “A castle?” said Mason. “Nope.” “A... pizza?” said James. “WHY would a pizza have keys?” said Gus. “...Extra-cheese keys?” said James. Everyone giggled.",
            "Last guess. Ethan closed both eyes and thought. “Keys... space... enter...” Suddenly Ethan's eyes popped open. “It's something we all use every day!”",
            "“It's a KEYBOARD!” said Ethan. “It has keys, a space bar and an Enter key!”",
            "The gate went quiet. Then its stone mouth fell open. “Nobody has solved that one in a hundred years,” said Gus. CLUNK-CLUNK-CLANG! The gate swung open, and a second key, a golden one, dropped into Ethan's hand.",
            "“Great job, Ethan!” said Daniel. “Your brain is amazing.” Ethan grinned. “Just a regular brain. A very good one.”",
        ], challenge="Can you make up your own riddle? Ask someone at home and see if they can solve it!"),
        dict(title="The Cave of Echoes", scene="cave", paras=[
            "Next came a dark, gloomy cave. “Hello?” called Raffi. “Hello... hello... hello...” answered the echo. “Cool!” said James. “James is the best! ...best... best...” “Funny,” said Mason. “The echo agrees.”",
            "Deep inside the cave, the squad heard a noise like a thousand tractors snoring: ZZZZZZRRRRRRR.",
            "They tiptoed around the corner and froze. In the middle of the tunnel lay the biggest, fluffiest creature they had ever seen. It was as big as a bus, as purple as a plum, and had paws the size of dustbin lids. It was blocking the whole tunnel.",
            "Ethan checked the Mayor's scroll. “It says here that this is a Snorebear. Snorebears are friendly, but terrified of thunder.”",
            "“We need to wake it up... gently,” said Daniel. “Raffi?”",
            "Raffi gulped. Then Raffi stood tall, tiptoed forward and tapped one giant paw. “Excuse me, Snorebear?”",
            "One enormous eye opened. Then the other. The Snorebear sat up and sniffled. “Is the thunder gone?” it asked in a tiny, shaky voice. “The storm has been rumbling for days. I'm too scared to move.”",
            "“We're going to stop the storm,” said Raffi. “I promise.” And Raffi gave the huge creature a gentle pat on the nose.",
            "“But I'm still scared,” sniffled Snuffles, shaking so hard that little stones fell from the ceiling.",
            "James stepped forward. “Hey, Snuffles, want to hear a joke? What do you call a bear with no teeth?”",
            "Snuffles giggled. Then Snuffles chuckled. Then Snuffles laughed so hard that the whole cave shook. “HAR HAR HAR! A gummy bear!” Little glowing stones fell from the ceiling like confetti.",
            "“I haven't laughed in years,” said Snuffles, wiping away a tear. “You may pass. And take this.” Snuffles gave Raffi a glowing blue stone. “It shines when someone nearby is sad. May it help you.”",
            "The squad squeezed past, while Snuffles waved a giant paw goodbye. Daniel put the glowing stone in his pocket. It felt warm.",
        ], challenge="Do you have a joke that makes people laugh? Tell it to someone today!"),
        dict(title="Kai Takes Flight", scene="tower", paras=[
            "At last, the squad reached the bottom of the Storm Tower. It was as tall as a hundred houses, wrapped in swirling gray clouds, with lightning flashing around the roof. The wind blew so hard it could flip a pancake.",
            "“There's no door,” said Ethan. “Only one window, right at the top.” Everyone looked up. Way, way up.",
            "“We can't climb that,” said Mason. “We can only fly.” Everyone looked at Kai. Kai smiled calmly. “I do have a glider.”",
            "It was the kite from Kai's backpack! On Skyhaven, everything grows bigger and better. It stretched and puffed and became a real glider, with bright red wings and a seat for two.",
            "“The wind is too strong for a normal takeoff,” said Kai. “We need a launch.” Daniel took charge. “Okay, team. Here's the plan.”",
            "“Mason, build a ramp! Riley, run beside the glider and push as hard as you can. Ethan, tell us the best angle. Raffi, check the ropes. James, cheer the loudest!” “Loud is my superpower,” said James.",
            "Daniel climbed into the second seat. Mason's ramp was ready. “Thirty degrees,” said Ethan. “Exactly.” Riley pushed. James yelled, “GO GO GO GO GO!” The glider zoomed down the ramp and... WHOOSH! It flew.",
            "The wind pushed and pulled. Lightning flashed. Daniel held on tight and squeezed his eyes shut. “Daniel, open your eyes,” said Kai calmly. “Look. We're flying.” Daniel looked. Clouds were below them. Skyhaven's green hills spread out like a map. “WOW.”",
            "Kai steered through the wind like a fish through water: left, right, a loop-the-loop and around the tower. Up, up, up, until the window was right in front of them. They landed gently on a little balcony.",
            "Down on the ground, the squad cheered so loud that the Snorebear heard it in the cave. Daniel took a deep breath and pushed the window open.",
        ], challenge="If you could fly anywhere in a glider, where would you go?"),
        dict(title="Meet Grumble", scene="cloud", paras=[
            "Inside the tower was one gigantic room, dark and cold. In the middle, on a huge chair, sat the biggest gray cloud Daniel had ever seen. It had two big sad eyes and a droopy mouth. In its arms (well, puffs) it held the Great Golden Star, glowing softly.",
            "“GO AWAY!” boomed the cloud. Thunder rumbled. Rain dripped from its eyes. “Everybody runs away when I come near! GO AWAY!”",
            "Daniel's pocket felt warm. He pulled out Snuffles's glowing stone. It was shining brighter than ever, as bright as a lamp. “It's glowing because someone nearby is sad,” whispered Daniel. He looked at the cloud. “It's you.”",
            "Daniel stepped forward. His knees were wobbling, but he remembered what a good leader does: listen. “Hi. I'm Daniel. What's your name?”",
            "“...Grumble,” sniffled the cloud. “My name is Grumble.”",
            "“Why did you take the Star, Grumble?” asked Daniel gently.",
            "Grumble's lip wobbled. “I live all alone in this dark tower. Every time I rumble, everybody runs away. I just wanted something shiny and warm, so that someone, anyone, would come and visit me.” A tear rolled down, plip! and became a tiny raindrop.",
            "Daniel nodded slowly. “I think I understand. You're not scary, Grumble. You're lonely.” “...Am I?” whispered Grumble.",
            "The squad came forward. “Hi, Grumble,” said Riley. “I can run faster than a rocket.” “I can build you a comfy chair,” said Mason. Raffi gave the cloud a big pat. “You're so fluffy.” “I'll teach you riddles,” said Ethan. “Want to fly my kite?” asked Kai. “And I've got a joke,” said James. “What do clouds wear under their clothes?” “...What?” said Grumble. “THUNDERWEAR!”",
            "Grumble's big sad face wobbled. Then it twitched. Then Grumble burst out laughing, a huge rumbly laugh like a hundred drums. “HAHAHAHA! Thunderwear!” And the raindrops turned into twinkling sparkles.",
            "“Nobody ever visited me before,” said Grumble. “I'm sorry I took the Star. Here you go.” Grumble handed the Great Golden Star to Daniel. It glowed bright and warm.",
            "“Thank you,” said Daniel. “And you know what? You can visit Skyhaven any time you like.”",
        ], challenge="Has someone at your school ever been lonely? What kind thing could you do?"),
        dict(title="The Great Skyhaven Party", scene="party", paras=[
            "Daniel raised the Star high. A beam of golden light shot out of the tower and up into the sky. The whole island shuddered. Then, slowly, Skyhaven rose higher and higher, standing straight again.",
            "Down in the village, everybody cheered. Mayor Fluff threw the top hat into the air. Captain Pancake flapped around the bus, yelling “HIP HIP HOORAY!”",
            "That night, Skyhaven threw the biggest party in history, and Grumble was the guest of honor. Grumble sat in the middle of the village, rumbling with laughter, and the sparkles rained down on everyone like glitter.",
            "Mayor Fluff gave every member of the squad a golden medal: Riley (Fastest Feet), Mason (Master Builder), James (Giggle Champion), Raffi (Bravest Heart), Ethan (Super Brain) and Kai (Sky Pilot). Daniel got the Leader's Medal: “For listening, and for kindness.”",
            "They danced, they ate pancakes (thanks to Captain Pancake) and they ate cloud candy floss in every flavor. Even Snuffles the Snorebear showed up, laughing at James's jokes.",
            "At sunset, Captain Pancake honked the bus horn. “All aboard! Time to go home!” The squad waved goodbye to Grumble, who promised, “I'll rain sparkles every Saturday!”",
            "On the way home, they sat in the bus, tired and happy. Daniel looked at his friends. Riley, Mason, James, Raffi, Ethan and Kai were the best squad in the whole wide world.",
            "The bus landed in Daniel's street. Daniel looked at his clock. It was still 10 o'clock. “How is that possible?” he laughed.",
            "In his hand, the golden ticket glowed one last time. New words appeared in curly purple letters:",
            ("q", "THANK YOU, HERO SQUAD!<br/>SEE YOU AT THE NEXT ADVENTURE..."),
            "Daniel smiled. He couldn't wait.",
        ], challenge="What should the squad's NEXT adventure be? Write or draw your idea on the next page!"),
    ],
    quiz=[
        ("What did Daniel find in his backpack?", "A golden ticket."),
        ("Who drives the Sky Bus?", "Captain Pancake, a giant green parrot."),
        ("What keeps Skyhaven floating?", "The Great Golden Star."),
        ("Who figured out the pattern in the wind?", "Riley."),
        ("What was making the CHOMP sound in the chasm?", "A hamster."),
        ("What was the answer to Gus's riddle?", "A keyboard."),
        ("What is Snuffles the Snorebear afraid of?", "Thunder."),
        ("Who flew the glider?", "Kai."),
        ("Why did Grumble take the Star?", "Grumble was lonely and wanted visitors."),
        ("What special thing did Daniel do that helped Grumble?", "Daniel listened and was kind."),
    ],
)

AF = dict(
    code="AF",
    file="Daniel_en_die_Hemelhawe-span_AF.pdf",
    title="Daniel en die Hemelhawe-span",
    cover_top="'N STORIE OOR VRIENDSKAP, MOED EN GOEDHARTIGHEID",
    cover_for="Geskryf vir Daniel en sy span",
    cover_names="Riley · Mason · James · Raffi · Ethan · Kai",
    ui=dict(
        chapter="HOOFSTUK", challenge="SPAN-UITDAGING", the_end="DIE EINDE",
        the_end_sub="(vir eers!)", dedication_title="Vir Daniel",
        dedication=("Hierdie boek is vir Daniel, die beste leier wat 'n span kan hê, en vir sy vriende "
                    "Riley, Mason, James, Raffi, Ethan en Kai. Ware vriende maak elke avontuur beter."),
        squad_title="Ontmoet die Span", talent="Supertalent", motto="Leuse",
        map_title="Kaart van Hemelhawe-eiland", map_sub="Volg die pad na die Stormtoring! Merk elke halte af wanneer jy die hoofstuk klaar gelees het.",
        quiz_title="Span-vasvra", quiz_sub="Hoe goed het jy gelees? Antwoord in volsinne. Die antwoorde is onder aan die bladsy.",
        answers="Antwoorde:", next_title="Jou Volgende Avontuur!",
        next_text="Waarheen moet die Hemelhawe-span volgende gaan? Teken die plek en skryf wat gebeur.",
        draw="Teken dit hier:", write="Skryf daaroor:", page="Bladsy", fan="",
    ),
    map_stops=["Landing", "Wankelbrug", "Byt-kloof", "Raaiselpoort", "Eggogrot", "Stormtoring"],
    squad=[
        ("Daniel", "Leier en Luisteraar", "Saam kan ons enigiets doen!", "#5B2A9E"),
        ("Riley", "Vinnigste Voete", "Moenie ophou hardloop nie!", "#E4572E"),
        ("Mason", "Meesterbouer", "Ek kan dit bou.", "#2D9CDB"),
        ("James", "Grapmasjien", "Lag is 'n supermag!", "#E0A800"),
        ("Raffi", "Dapperste Hart", "Wees dapper, wees gaaf.", "#2EAD6B"),
        ("Ethan", "Superbrein", "Dink eers, doen dan.", "#7B4BC8"),
        ("Kai", "Hemelvlieënier", "Bly kalm en vlieg hoog.", "#17A2B8"),
    ],
    chapters=[
        dict(title="Die Goue Kaartjie", scene="ticket", paras=[
            "Dit was die eerste dag van die skoolvakansie, en Daniel was verveeld. Nie 'n bietjie verveeld nie. Super-mega-ekstra verveeld.",
            "Hy het op sy bed gelê en 'n bal teen die plafon gegooi toe iets KLINK in sy skoolsak maak.",
            "“Dis snaaks,” sê Daniel. “Ek het niks ingepak wat klink nie.”",
            "Hy trek die sak oop en haal 'n blink, goue kaartjie uit. Dit het geskyn soos 'n klein sonnetjie. In krullerige pers letters het dit gesê:",
            ("q", "HEMELHAWE SOEK 'N HELDESPAN!<br/>Sewe spelers gesoek. Die bus vertrek presies tienuur. Moenie laat wees nie!"),
            "Daniel kyk na sy horlosie. Dit was 9:58.",
            "“TWEE MINUTE?!” skree hy.",
            "Hy gryp sy foon en stuur die vinnigste boodskap van sy lewe: “NOODGEVAL! Goue kaartjie! Span nou nodig! Ontmoet my buite!”",
            "Ses antwoorde het ingeflits voor hy eens sy skoene kon vind. Riley: “Ek hardloop!” Mason: “Ek bring my gereedskap.” James: “Is dit 'n grap? Ek HOU daarvan.” Raffi: “Ek kom! Ek is dapper!” Ethan: “Interessant. Ek bereken die vinnigste pad.” Kai: “Ek kyk reeds na die lug.”",
            "Binne 'n minuut het ses vriende om die draai kom gly. Riley was eerste (natuurlik). Mason het aangeklink met 'n gereedskapsgordel. James het reeds gelag. Raffi het 'n superheld-mantel aangehad. Ethan het 'n kaart vasgehou. Kai het 'n vlieër uit 'n skoolsak laat uitsteek.",
            "Toe, presies tienuur, het die lug HONK HONK gesê! 'n Reusagtige blou bus met draaiende silwer skroewe het uit die lug gewerwel en reg in Daniel se straat geland.",
            "Die deure swaai oop. “Almal aan boord!” skree 'n stem.",
        ], challenge="As JY 'n goue kaartjie gevind het, waarheen sou jy wou gaan?"),
        dict(title="Almal aan boord by die Hemelbus", scene="bus", paras=[
            "Binne het die bus na pannekoeke geruik. Die bestuurder was 'n reusagtige groen papegaai met 'n klein kapteinshoedjie.",
            "“Welkom aan boord, span!” skree Kaptein Pannekoek. “Hou jou hande binne die bus, jou voete van die sitplekke af en jou peuselhappies in jou maag!”",
            "Die bus styg op met 'n WHOOOOSH. Huise het soos speelgoed gelyk. Karre het soos miertjies gelyk. Daniel druk sy neus teen die venster en grinnik. Toe kyk hy rond na sy vriende.",
            "Riley was die vinnigste hardloper in die hele skool. Riley se skoenveters was altyd dubbeld vasgemaak, net ingeval.",
            "Mason kon enigiets uit enigiets bou. Eendag het Mason 'n skaatsplank van 'n graankosdoos en drie lepels gemaak. (Dit het net 'n bietjie gewerk.)",
            "James was die snaaksste kind wat enigiemand geken het. James het 'n grap vir elke dag van die jaar, en vir skrikkeljare ook.",
            "Raffi was die dapperste. Raffi het eendag 'n hond gestreel wat groter as 'n bank was en gesê: “Goeie hond!”",
            "Ethan was die slimste. Ethan kon 'n raaisel vinniger oplos as wat jy “raaisel” kon sê.",
            "Kai was die kalmste en die beste om vlieërs te laat vlieg. Kai se vlieërs het hoër as die wolke gevlieg.",
            "En Daniel? Daniel was die span se leier, want Daniel was 'n uitstekende luisteraar en het almal laat voel hulle is deel van die span.",
            "“So wat is die sending?” vra Daniel.",
            "Kaptein Pannekoek se gesig word ernstig. “Die Hemelhawe-eiland swewe danksy die Groot Goue Ster. Gisteraand het die Storm dit gesteel. Nou sink die eiland, elke uur 'n bietjie meer. As ons nie die Ster terugkry nie, sal Hemelhawe neerstort!”",
            "“Moenie bekommerd wees nie,” sê Daniel. “Ons kry dit terug. Saam.”",
            "Buite die venster verskyn 'n swewende eiland bo die wolke, met watervalle wat OPWAARTS die lug in stort. “Volgende halte,” skree Kaptein Pannekoek, “Hemelhawe!”",
        ], challenge="Watter vriend se talent sal jy die graagste wil hê? Hoekom?"),
        dict(title="Hemelhawe in die Moeilikheid", scene="island", paras=[
            "Die bus het met 'n hop geland. Alles op Hemelhawe was 'n bietjie skuins. 'n Bank het verbygegly. 'n Gieter het weggerol. James het pas 'n roomys gekry toe die grond kantel en die roomys van die horinkie af wegglip. “My roomys ontsnap!” kerm James.",
            "'n Piepklein lama met 'n reusehoed het op 'n kissie gestaan. “Ek is Burgemeester Pluis,” sê die lama. “Dank die hemel dat julle hier is!”",
            "Die burgemeester rol 'n lang boekrol oop. “Die Storm bly in die Stormtoring, bo-op die Skewe Berg. Om daar te kom, moet julle vyf toetse slaag:”",
            ("list", ["Die Wankelbrug", "Die Byt-kloof", "Die Raaiselpoort", "Die Eggogrot", "Die Stormtoring self"]),
            "“Maklik soos pannekoek!” sê James. Almal kyk na James. “...Goed, miskien nie maklik nie. Maar wel pannekoek.”",
            "Burgemeester Pluis gee vir elke lid van die span 'n goue kenteken in die vorm van 'n ster. Daniel pen syne vas en voel 'n warm tintel. “Span,” sê Daniel, “kom ons gaan red Hemelhawe!”",
            "Die span marsjeer na die Skewe Berg. Agter hulle kantel die eiland nog 'n bietjie meer. Tik-tok, tik-tok.",
        ], challenge="Maak 'n snaakse naam vir 'n plek op Hemelhawe op. Wat sal dit wees?"),
        dict(title="Riley en die Wankelbrug", scene="bridge", paras=[
            "Die eerste toets was die Wankelbrug. Dit was van ou houtplanke gemaak en het oor 'n rivier van wit, donserige wolke gehang. En dit het gewankel soos jellie op 'n trampolien.",
            "WHOOOSH! 'n Sterk windvlaag het gewaai. Twee planke het afgevlieg en in die lug weggedraai.",
            "“Niemand moet paniekerig raak nie,” sê Daniel. “Riley, wat sien jy?”",
            "Riley kyk mooi na die brug. “Die wind kom in golwe,” sê Riley. “Groot vlaag... pouse... groot vlaag... pouse. As ons in die pouse hardloop, sal ons dit maak!”",
            "“Volg my voetspore,” sê Riley. “Trap waar ek trap!”",
            "Riley het getel: “Een... twee... DRIE!” en soos 'n vuurpyl oor die brug gesoem. Spring-spring-hop! Anderkant het Riley met albei arms gewuif.",
            "Een vir een het die span gevolg. Mason het gegly. Ethan het hardop getel. Raffi was dapper totdat die brug wiebel-wiebel gaan, toe sê Raffi: “Eeeek!” maar gaan aan. James het so hard gelag dat James amper afgeval het, maar Kai gryp net betyds 'n hand.",
            "Daniel was laaste. WHOOSH! Die wind het gewaai, maar Daniel het vir die pouse gewag en toe met al die spoed in sy bene gehardloop. Hy het op vaste grond gespring, en die brug het agter hom weggedraai.",
            "Aan die einde van die brug het 'n klein silwer sleutel aan 'n haak gehang. Riley tel dit op. “Een sleutel af. Vier toetse oor!”",
        ], challenge="Riley het 'n patroon in die wind raakgesien. Kan jy 'n patroon in jou klaskamer of by die huis vind?"),
        dict(title="Mason se Groot Bouwerk", scene="chasm", paras=[
            "Die volgende toets was die Byt-kloof. Dit was 'n reusagtige gaping in die grond, so wyd dat die ander kant piepklein gelyk het. Onder in die kloof het iets BYT BYT BYT gemaak.",
            "“Nee dankie,” sê James. “Ek val nie daarin nie.”",
            "Groot swewende rotse en ou planke het deur die lug verbygedryf. Mason se oë het begin blink. “Ek kan met daardie goed bou,” sê Mason.",
            "“Hoeveel het ons nodig?” vra Daniel. Ethan haal 'n maatband uit. “Die gaping is presies 12 meter,” sê Ethan. “Ons het ten minste 13 meter brug nodig om veilig te wees. En 'n stewige oprit aan elke kant.”",
            "“Perfek,” sê Mason en kraak sy vingers. “Almal, ek het spanwerk nodig.”",
            "Almal het 'n werk gekry. Riley het rondgejaag om planke te versamel. Kai het toue met perfekte knope vasgemaak. Raffi het die leer vasgehou. James het grappe vertel om almal vrolik te hou (“Hoekom was die wiskundeboek hartseer? Dit het te veel probleme gehad!”). Ethan het elke meting twee keer nagegaan. Daniel het gereedskap vir Mason aangegee en gesê: “Jy kan dit doen.”",
            "Mason het gehamer, gesaag en gewikkel. BANG! KLANG! KLONK! Stadig het 'n brug oor die kloof gegroei, met relings en alles.",
            "Onder in die kloof het die BYT-geluid harder geword. “Moenie afkyk nie,” sê Daniel. “Kyk na die brug. Kyk na jou vriende.” Een vir een het hulle oorgesteek. Halfpad oor loer Raffi oor die rand. “Span, die byter is 'n hamster!” Dit was so groot soos 'n sokkerbal, met 'n wiebelneus. Raffi gooi 'n halwe toebroodjie af. BYT! Die hamster het gespin.",
            "Aan die ander kant klop Mason die laaste plank. “Ek het mos gesê ek kan enigiets uit enigiets bou.”",
        ], challenge="Wat sal JY bou om oor die kloof te kom? Teken dit!"),
        dict(title="Die Raaiselpoort", scene="gate", paras=[
            "Aan die einde van 'n lang, kronkelende pad het 'n groot klippoort gestaan, met 'n reuse gesig in die middel uitgekerf. Die gesig het slaperige oë en 'n baie lang snor gehad.",
            "“Ek is Gus, die Poortwagter,” rommel die poort. “Om verby te kom, moet julle my raaisel beantwoord. Julle kry drie pogings.”",
            "Die poort maak sy keel skoon. “Ek het sleutels, maar geen slotte nie. Ek het 'n spasie, maar geen kamer nie. Jy kan 'Enter' druk, maar jy kan nie na binne gaan nie. Wat is ek?”",
            "“'n Klavier?” raai Raffi. “Nee,” sê Gus. “'n Kasteel?” sê Mason. “Nee.” “'n... pizza?” sê James. “WAAROM sou 'n pizza sleutels hê?” sê Gus. “...Ekstra-kaas-sleutels?” sê James. Almal het gegiggel.",
            "Laaste kans. Ethan maak albei oë toe en dink. “Sleutels... spasie... Enter...” Skielik spring Ethan se oë oop. “Dis iets wat ons almal elke dag gebruik!”",
            "“Dis 'n SLEUTELBORD!” sê Ethan. “Dit het sleutels, 'n spasiebalk en 'n Enter-sleutel!”",
            "Die poort was doodstil. Toe val sy klipmond oop. “Niemand het dit al in honderd jaar opgelos nie,” sê Gus. KLONK-KLONK-KLANG! Die poort swaai oop en 'n tweede sleutel, 'n goue een, val in Ethan se hand.",
            "“Mooi so, Ethan!” sê Daniel. “Jou brein is wonderlik.” Ethan grinnik. “Net 'n gewone brein. 'n Baie goeie een.”",
        ], challenge="Kan jy jou eie raaisel maak? Vra iemand by die huis en kyk of hulle dit kan oplos!"),
        dict(title="Die Eggogrot", scene="cave", paras=[
            "Daarna het 'n donker, gure grot gekom. “Hallo?” roep Raffi. “Hallo... hallo... hallo...” antwoord die eggo. “Cool!” sê James. “James is die beste! ...beste... beste...” “Snaaks,” sê Mason. “Die eggo stem saam.”",
            "Diep in die grot hoor die span 'n geluid soos duisend trekkers wat snork: ZZZZZZRRRRRRR.",
            "Hulle het om die draai getiptoe en verstar. Middel in die tonnel het die grootste, donserigste wese gelê wat hulle nog ooit gesien het. Dit was so groot soos 'n bus, so pers soos 'n pruim, met pote so groot soos vullisdekselle. Dit het die hele tonnel versper.",
            "Ethan kyk na die burgemeester se boekrol. “Hier staan dit is 'n Snorkbeer. Snorkberes is vriendelik, maar doodbang vir donder.”",
            "“Ons moet dit wakker maak... saggies,” sê Daniel. “Raffi?”",
            "Raffi sluk. Toe staan Raffi regop, tiptoe vorentoe en tik aan een reuse poot. “Verskoon my, Snorkbeer?”",
            "Een enorme oog gaan oop. Toe die ander. Die Snorkbeer sit regop en snuif. “Is die donder weg?” vra dit met 'n klein, bewerige stemmetjie. “Die storm rommel al dae lank. Ek is te bang om te beweeg.”",
            "“Ons gaan die storm stop,” sê Raffi. “Ek belowe.” En Raffi gee die reuse-wese 'n sagte klop op die neus.",
            "“Maar ek is steeds bang,” snuif Snuffel, so erg bewerig dat klein klippies van die dak afval.",
            "James stap vorentoe. “Haai, Snuffel, wil jy 'n grap hoor? Wat noem jy 'n beer sonder tande?”",
            "Snuffel giggel. Toe grinnik Snuffel. Toe lag Snuffel so hard dat die hele grot geskud het. “HAR HAR HAR! 'n Jellie-beertjie!” Klein, gloeiende klippies het soos konfetti van die dak geval.",
            "“Ek het in jare nie gelag nie,” sê Snuffel en vee 'n traan af. “Julle mag verbygaan. En neem hierdie.” Snuffel gee vir Raffi 'n gloeiende blou klip. “Dit skyn wanneer iemand naby hartseer is. Mag dit julle help.”",
            "Die span druk verby terwyl Snuffel met 'n reuse poot totsiens waai. Daniel sit die gloeiende klip in sy sak. Dit voel warm.",
        ], challenge="Het jy 'n grap wat mense laat lag? Vertel dit vandag vir iemand!"),
        dict(title="Kai neem Vlug", scene="tower", paras=[
            "Uiteindelik het die span die voet van die Stormtoring bereik. Dit was so hoog soos honderd huise, toegedraai in warrelende grys wolke, met weerlig wat om die dak flits. Die wind het so hard gewaai dat dit 'n pannekoek kon omflip.",
            "“Daar is geen deur nie,” sê Ethan. “Net een venster, heel bo.” Almal kyk op. Ver, ver op.",
            "“Ons kan nie daarteen uitklim nie,” sê Mason. “Ons kan net vlieg.” Almal kyk na Kai. Kai glimlag kalm. “Ek het wel 'n sweeftuig.”",
            "Dit was die vlieër uit Kai se skoolsak! Op Hemelhawe word alles groter en beter. Dit het gerek en opgeblaas en 'n regte sweeftuig geword, met helderrooi vlerke en 'n sitplek vir twee.",
            "“Die wind is te sterk vir 'n gewone opstyg,” sê Kai. “Ons het 'n lansering nodig.” Daniel neem beheer. “Reg, span. Hier is die plan.”",
            "“Mason, bou 'n oprit! Riley, hardloop langs die sweeftuig en stoot so hard jy kan. Ethan, sê vir ons die beste hoek. Raffi, kyk na die toue. James, moedig ons die hardste aan!” “Hard is my supermag,” sê James.",
            "Daniel klim in die tweede sitplek. Mason se oprit was gereed. “Dertig grade,” sê Ethan. “Presies.” Riley stoot. James skree: “GAAN GAAN GAAN GAAN GAAN!” Die sweeftuig soem teen die oprit af en... WHOOSH! Dit het gevlieg.",
            "Die wind het gestoot en getrek. Weerlig het geflits. Daniel het styf vasgehou en sy oë styf toegedruk. “Daniel, maak jou oë oop,” sê Kai kalm. “Kyk. Ons vlieg.” Daniel kyk. Wolke was onder hulle. Hemelhawe se groen heuwels het soos 'n kaart uitgesprei. “WOW.”",
            "Kai het deur die wind gestuur soos 'n vis deur water: links, regs, 'n lus-die-lus en om die toring. Op, op, op, totdat die venster reg voor hulle was. Hulle het saggies op 'n klein balkon geland.",
            "Onder op die grond het die span so hard gejuig dat die Snorkbeer dit in die grot kon hoor. Daniel haal diep asem en stoot die venster oop.",
        ], challenge="As jy met 'n sweeftuig enige plek kon vlieg, waarheen sal jy gaan?"),
        dict(title="Ontmoet Grommel", scene="cloud", paras=[
            "Binne die toring was een reusagtige kamer, donker en koud. Middel-in, op 'n groot stoel, het die grootste grys wolk gesit wat Daniel nog ooit gesien het. Dit het twee groot hartseer oë en 'n hangende mond gehad. In sy arms (wel, pluise) het dit die Groot Goue Ster gehou, wat sag geskyn het.",
            "“GAAN WEG!” bulder die wolk. Donder het gerommel. Reën het uit sy oë gedrup. “Almal hardloop weg as ek naby kom! GAAN WEG!”",
            "Daniel se sak het warm gevoel. Hy trek Snuffel se gloeiende klip uit. Dit het helderder as ooit geskyn, so helder soos 'n lamp. “Dit gloei omdat iemand naby hartseer is,” fluister Daniel. Hy kyk na die wolk. “Dis jy.”",
            "Daniel stap vorentoe. Sy knieë het gebewe, maar hy het onthou wat 'n goeie leier doen: luister. “Hallo. Ek is Daniel. Wat is jou naam?”",
            "“...Grommel,” snuif die wolk. “My naam is Grommel.”",
            "“Hoekom het jy die Ster geneem, Grommel?” vra Daniel saggies.",
            "Grommel se lip bewe. “Ek bly heeltemal alleen in hierdie donker toring. Elke keer as ek rommel, hardloop almal weg. Ek wou net iets blink en warm hê, sodat iemand, enigiemand, my sou kom besoek.” 'n Traan het afgerol, plip! en 'n klein reëndruppel geword.",
            "Daniel knik stadig. “Ek dink ek verstaan. Jy is nie skrikwekkend nie, Grommel. Jy is eensaam.” “...Is ek?” fluister Grommel.",
            "Die span kom nader. “Hallo, Grommel,” sê Riley. “Ek kan vinniger as 'n vuurpyl hardloop.” “Ek kan vir jou 'n gemaklike stoel bou,” sê Mason. Raffi gee die wolk 'n groot klop. “Jy is so donserig.” “Ek sal jou raaisels leer,” sê Ethan. “Wil jy my vlieër laat vlieg?” vra Kai. “En ek het 'n grap,” sê James. “Wat dra wolke onder hul klere?” “...Wat?” vra Grommel. “DONDERBROEKIES!”",
            "Grommel se groot hartseer gesig bewe. Toe ruk dit. Toe bars Grommel uit van die lag, 'n reusagtige rommellag soos honderd tromme. “HAHAHAHA! Donderbroekies!” En die reëndruppels het in flikkerende vonkies verander.",
            "“Niemand het my nog ooit besoek nie,” sê Grommel. “Ek is jammer dat ek die Ster geneem het. Hier is dit.” Grommel gee die Groot Goue Ster vir Daniel. Dit het helder en warm geskyn.",
            "“Dankie,” sê Daniel. “En weet jy wat? Jy kan Hemelhawe besoek wanneer jy wil.”",
        ], challenge="Was iemand by jou skool al eensaam? Watter goeie ding kan jy doen?"),
        dict(title="Die Groot Hemelhawe-partytjie", scene="party", paras=[
            "Daniel hou die Ster hoog. 'n Straal goue lig skiet uit die toring en die lug in. Die hele eiland het gebewe. Toe, stadig, het Hemelhawe hoër en hoër gestyg, en weer reguit gestaan.",
            "Onder in die dorp het almal gejuig. Burgemeester Pluis het sy hoed in die lug gegooi. Kaptein Pannekoek het om die bus gefladder en “HIP HIP HOERA!” geskree.",
            "Daardie aand het Hemelhawe die grootste partytjie in die geskiedenis gehou, en Grommel was die eregas. Grommel het in die middel van die dorp gesit en gerommel van die lag, en die vonkies het soos glinster op almal gereën.",
            "Burgemeester Pluis het vir elke lid van die span 'n goue medalje gegee: Riley (Vinnigste Voete), Mason (Meesterbouer), James (Gierlag-Kampioen), Raffi (Dapperste Hart), Ethan (Superbrein) en Kai (Hemelvlieënier). Daniel het die Leier se Medalje gekry: “Vir luister, en vir goedhartigheid.”",
            "Hulle het gedans, pannekoeke geëet (met dank aan Kaptein Pannekoek) en wolksuikerspin in elke geur geëet. Selfs Snuffel die Snorkbeer het opgedaag en vir James se grappe gelag.",
            "Met sonsondergang het Kaptein Pannekoek die bus se toeter gelui. “Almal aan boord! Tyd om huis toe te gaan!” Die span het vir Grommel totsiens gewuif, wat belowe het: “Ek sal elke saterdag vonkies reën!”",
            "Op pad huis toe het hulle moeg en gelukkig in die bus gesit. Daniel kyk na sy vriende. Riley, Mason, James, Raffi, Ethan en Kai was die beste span in die hele wye wêreld.",
            "Die bus het in Daniel se straat geland. Daniel kyk na sy horlosie. Dit was nog steeds tienuur. “Hoe is dit moontlik?” lag hy.",
            "In sy hand het die goue kaartjie een laaste keer geskyn. Nuwe woorde het in krullerige pers letters verskyn:",
            ("q", "DANKIE, HELDESPAN!<br/>ONS SIEN JULLE BY DIE VOLGENDE AVONTUUR..."),
            "Daniel glimlag. Hy kon nie wag nie.",
        ], challenge="Wat moet die span se VOLGENDE avontuur wees? Skryf of teken jou idee op die volgende bladsy!"),
    ],
    quiz=[
        ("Wat het Daniel in sy skoolsak gevind?", "'n Goue kaartjie."),
        ("Wie bestuur die Hemelbus?", "Kaptein Pannekoek, 'n reusagtige groen papegaai."),
        ("Wat hou Hemelhawe in die lug?", "Die Groot Goue Ster."),
        ("Wie het die patroon in die wind uitgepluis?", "Riley."),
        ("Wat het die BYT-geluid in die kloof gemaak?", "'n Hamster."),
        ("Wat was die antwoord op Gus se raaisel?", "'n Sleutelbord."),
        ("Waarvoor is Snuffel die Snorkbeer bang?", "Donder."),
        ("Wie het die sweeftuig gevlieg?", "Kai."),
        ("Hoekom het Grommel die Ster geneem?", "Grommel was eensaam en wou besoekers hê."),
        ("Watter spesiale ding het Daniel gedoen om Grommel te help?", "Daniel het geluister en was gaaf."),
    ],
)
